version: '3'
services:
  filestorage:
    image: minio/minio:RELEASE.2020-03-05T01-04-19Z
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: eu-west-1
    ports:
      - 9000:9000
    command: server /data
  sftp:
    image: atmoz/sftp
    ports:
    - "22:22"
    command: foo:pass:::upload
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
    - "10000:10000"
    command: azurite-blob --blobHost 0.0.0.0
  configure-buckets:
    image: minio/mc:RELEASE.2020-02-20T23-49-54Z
    entrypoint: sh
    depends_on:
      - filestorage
    command: -c "sleep 5 && mc config host add minio http://filestorage:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    # && mc mb --region=eu-west-1 minio/meltwater-drone-default"
